<?php

/**
 * @file
 * Contains svv_dictionary.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function svv_dictionary_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the svv_dictionary module.
    case 'help.page.svv_dictionary':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SVV Dictionary') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function svv_dictionary_theme() {
  return [
    'svv_dictionary' => [
      'render element' => 'children',
    ],
  ];
}
