#!/usr/bin/env bash

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
DOW=$(date +%u)
DRUSH="fin drush"
COMPOSER="fin composer"

#-------------------------- END: Settings --------------------------------

fin exec "sudo composer --version"
fin exec "sudo composer selfupdate --2"
fin exec "sudo composer --version"
