#!/bin/bash

DATE=`date '+%Y-%m-%d'`

# prompt user for actions
echo -n "Make backup? Type y or n and [ENTER]: "
read make_backup

# backup the code and the db
if [ $make_backup =  'y' ]; then
  echo "Backing up the database"
  $SERVER_CONNECTION "cd $REMOTE_PRODUCTION_DIR && $REMDRUSH sql-dump --result-file=$REMOTE_PROJECT_DIR/db/svv-bk-$DATE.sql"
fi

echo "Easing files and folder permissions"
$SERVER_CONNECTION "chmod 755 $REMOTE_PRODUCTION_DIR"
$SERVER_CONNECTION "find $REMOTE_PRODUCTION_DIR -type d -print0 | xargs -0 chmod 755"
$SERVER_CONNECTION "find $REMOTE_PRODUCTION_DIR -type f -print0 | xargs -0 chmod 644"
$SERVER_CONNECTION "chmod a+w $REMOTE_PRODUCTION_DIR/web/sites/default"
$SERVER_CONNECTION "chmod a+w $REMOTE_PRODUCTION_DIR/web/sites/default/settings.php"

echo "Syncing remote stage folder to remote production folder (replace the production code base)"
  $SERVER_CONNECTION "cd $REMOTE_STAGE_DIR && rsync -avz --progress --force --delete --progress --protect-args --exclude-from=deploy_exclude.txt $REMOTE_STAGE_DIR/ $REMOTE_PRODUCTION_DIR"

echo "Symlink settings and files"
$SERVER_CONNECTION "ln -sf $REMOTE_PROJECT_DIR/files $REMOTE_PRODUCTION_DIR/web/sites/default/files"

echo "Restrict folder & file permissions"
$SERVER_CONNECTION "chmod a-w $REMOTE_PRODUCTION_DIR/web/sites/default"
$SERVER_CONNECTION "chmod a-w $REMOTE_PRODUCTION_DIR/web/sites/default/settings.php"

echo "Deploying, running db & config updates"
$SERVER_CONNECTION "cd $REMOTE_PRODUCTION_DIR && $REMDRUSH updb -y && $REMDRUSH cr && $REMDRUSH cim -y && $REMDRUSH cron"

echo "Delete password protection on production"
$SERVER_CONNECTION "rm -f $REMOTE_PRODUCTION_DIR/.htaccess"


