#!/usr/bin/env bash

# provides actions to reset the the website to the state of the development
# branch.

DRUSH="fin drush"
COMPOSER="fin composer"

echo "Pulling latests code"
#git pull origin master

echo "Installing packages"
$COMPOSER install

echo "Clearing drush cache"
$DRUSH cc drush

echo "Displaying Drush status"
$DRUSH status

$DRUSH config-set system.file path.temporary 'sites/default/files/temp' -y

echo "Updating Drupal"
$DRUSH cr
$DRUSH updb -y
$DRUSH cim -y
$DRUSH entup -y
$DRUSH cr
