#!/usr/bin/env bash

fin up
git stash clear
git stash
git checkout master
git pull origin master
fin composer --version
fin composer validate
fin composer install
fin composer update
fin drush @self updb -y
fin drush @self cex -y
git add composer.lock
git add config/sync
git commit -m "updating composer packages"
git push origin master

echo "printing dev login link"
fin drush @dev uli
echo "printing stage login link"
fin drush @stage uli
echo "printing live login link"
fin drush @live uli

git stash pop
