#!/bin/bash
## Description: Install or use node.
## Usage: npm [flags] [args]
## Example: "npm use or npm install or npm run watch"
source /etc/profile && cd /var/www/html/web/themes/arcana && npm $@
