_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
langcode: nl
hotlink: false
origin: 'https://www.veldense-volkscultuur.nl'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
